### ISSUE TITLE
Prevents clicking off buffs in combat

### ISSUE THREAD

**Issue by dabadoo** [doadin/GridStatusExternals#13]
Something about this plugin is giving errors and preventing clicking off buffs in combat.

How to replicate: Be in combat. Right click a buff to try and remove it.

Fix: Disabling PlexusStatusExternals under statuses or disabling the plugin entirely.

Took a bit to figure out it was this specific plugin. Buggrabers assigns the error to different addons first and Plexus only shows as the one causing the error when I disabled things like bigdebuffs/weakauras/Losecontrol.

Exmaple:

			["message"] = "[ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CancelUnitBuff()'.",
			["time"] = "2023/09/23 20:35:41",
			["locals"] = "_ = Frame {\n RegisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n 0 = <userdata>\n UnregisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n SetScript = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n}\nevent = \"ADDON_ACTION_BLOCKED\"\nevents = <table> {\n ADDON_ACTION_BLOCKED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n ADDON_ACTION_FORBIDDEN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n PLAYER_LOGIN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:547\n LUA_WARNING = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:562\n ADDON_LOADED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:507\n}\n",
			["stack"] = "[string \"@Interface/AddOns/!BugGrabber/BugGrabber.lua\"]:481: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:481>\n[string \"=[C]\"]: in function `CancelUnitBuff'\n[string \"@Interface/FrameXML/BuffFrame.lua\"]:309: in function `BuffButton_OnClick'\n[string \"*BuffFrame.xml:41_OnClick\"]:1: in function <[string \"*BuffFrame.xml:41_OnClick\"]:1>",
			["session"] = 6131,
			["counter"] = 2,

After disabling bigdebuffs:

			["message"] = "[ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'CancelUnitBuff()'.",
			["time"] = "2023/09/23 20:36:59",
			["locals"] = "_ = Frame {\n RegisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n 0 = <userdata>\n UnregisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n SetScript = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n}\nevent = \"ADDON_ACTION_BLOCKED\"\nevents = <table> {\n ADDON_ACTION_BLOCKED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n ADDON_ACTION_FORBIDDEN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n PLAYER_LOGIN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:547\n LUA_WARNING = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:562\n ADDON_LOADED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:507\n}\n",
			["stack"] = "[string \"@Interface/AddOns/!BugGrabber/BugGrabber.lua\"]:481: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:481>\n[string \"=[C]\"]: in function `CancelUnitBuff'\n[string \"@Interface/FrameXML/BuffFrame.lua\"]:309: in function `BuffButton_OnClick'\n[string \"*BuffFrame.xml:41_OnClick\"]:1: in function <[string \"*BuffFrame.xml:41_OnClick\"]:1>",
			["session"] = 6132,
			["counter"] = 1,
			
Some time after having disabled WAs and other addons taking the blame:

			["message"] = "[ADDON_ACTION_BLOCKED] AddOn 'Plexus' tried to call the protected function 'CancelUnitBuff()'.",
			["time"] = "2023/09/23 20:38:35",
			["locals"] = "_ = Frame {\n RegisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n 0 = <userdata>\n UnregisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n SetScript = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n}\nevent = \"ADDON_ACTION_BLOCKED\"\nevents = <table> {\n ADDON_ACTION_BLOCKED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n ADDON_ACTION_FORBIDDEN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n PLAYER_LOGIN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:547\n LUA_WARNING = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:562\n ADDON_LOADED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:507\n}\n",
			["stack"] = "[string \"@Interface/AddOns/!BugGrabber/BugGrabber.lua\"]:481: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:481>\n[string \"=[C]\"]: in function `CancelUnitBuff'\n[string \"@Interface/FrameXML/BuffFrame.lua\"]:309: in function `BuffButton_OnClick'\n[string \"*BuffFrame.xml:41_OnClick\"]:1: in function <[string \"*BuffFrame.xml:41_OnClick\"]:1>",
			["session"] = 6137,
			["counter"] = 1,

Also getting this error. Unsure if related to this specific plugin:

			["message"] = "[ADDON_ACTION_BLOCKED] AddOn 'Plexus' tried to call the protected function 'ArenaEnemyFrames:SetPoint()'.",
			["time"] = "2023/09/23 20:38:22",
			["locals"] = "_ = Frame {\n RegisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n 0 = <userdata>\n UnregisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n SetScript = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:487\n}\nevent = \"ADDON_ACTION_BLOCKED\"\nevents = <table> {\n ADDON_ACTION_BLOCKED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n ADDON_ACTION_FORBIDDEN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:553\n PLAYER_LOGIN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:547\n LUA_WARNING = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:562\n ADDON_LOADED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:507\n}\n",
			["stack"] = "[string \"@Interface/AddOns/!BugGrabber/BugGrabber.lua\"]:481: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:481>\n[string \"=[C]\"]: in function `SetPoint'\n[string \"@Interface_Vanilla/FrameXML/UIParent.lua\"]:2568: in function `UIParentManageFramePositions'\n[string \"@Interface_Vanilla/FrameXML/UIParent.lua\"]:1868: in function <Interface_Vanilla/FrameXML/UIParent.lua:1855>\n[string \"=[C]\"]: in function `SetAttribute'\n[string \"@Interface_Vanilla/FrameXML/UIParent.lua\"]:2592: in function <Interface_Vanilla/FrameXML/UIParent.lua:2590>\n[string \"=[C]\"]: in function `Hide'\n[string \"@Interface/FrameXML/SecureStateDriver.lua\"]:103: in function <Interface/FrameXML/SecureStateDriver.lua:95>\n[string \"@Interface/FrameXML/SecureStateDriver.lua\"]:127: in function <Interface/FrameXML/SecureStateDriver.lua:119>",
			["session"] = 6136,
			["counter"] = 1,

**Comment by doadin** [comment]
I think this is related to https://github.com/Stanzilla/WoWUIBugs/issues/483 as the function mentioned in the code is not used anywhere in my code/PlexusStatusExternals.

**Comment by dabadoo** [comment]
Strange.
But the only addon I need to disable, for everything to behave like normal, is PlexusStatusExternals. So for now, it has to stay off ☹️ 
I forgot to mention this is classic era.

**Comment by doadin** [comment]
yea i looked at your other issue reports and figured you meant classic :) . And yes Things like this happen called taint in the code. As I mentioned the function in the error is no where in the code I use so it can not be coming from this. Also would be a very big coincidence that just as this blizzard taint has started this error started, I have not changed this code in a while the only thing changed is on blizzards end, and you can see other people posting in that link where the "blamed" addon is something different this is kind of what happens with taint. If/when this blizzard error gets fixed or a workaround if found if the issue still remains I will try and fix it. For now I will leave this open in case others run into it.

**Comment by doadin** [comment]
This should be fixed by blizz now. If you still have issues let me know. thanks!

**Comment by dabadoo** [comment]
Sorry for late response. Just tested it in raid last night.

Got this error again:
1x [ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CancelUnitBuff()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `CancelUnitBuff'
[string "@FrameXML/BuffFrame.lua"]:309: in function `BuffButton_OnClick'
[string "*BuffFrame.xml:41_OnClick"]:1: in function <[string "*BuffFrame.xml:41_OnClick"]:1>

Locals:
Skipped (In Encounter)

Disabling this plexus plugin made it go away.

**Comment by doadin** [comment]
Well still a blizzard issue, nothing I can do , as I mentioned before my code does not use "CancelUnitBuff" at all. Just have to wait for blizz to fix it. Sorry.

**Comment by doadin** [comment]
Just pushed an update v9.6.4, let me know if this works please, thanks!

**Comment by dabadoo** [comment]
That seems to have fixed it :) Cheers!
